/****** Object:  Table [dbo].[BI_DIM_TABLE]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[BI_DIM_TABLE](
	[BI_DIM_TABLE_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[BI_DIM_TABLE_LIBELLE] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_BI_DIM_TABLE_1] PRIMARY KEY CLUSTERED 
(
	[BI_DIM_TABLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
