/****** Object:  Table [dbo].[BI_PARAMETERS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[BI_PARAMETERS](
	[PARAM_ID] [int] IDENTITY(1,1) NOT NULL,
	[PARAM_TYPE] [int] NULL,
	[PARAM_VALUE] [nvarchar](50) NULL,
	[PARAM_ACTIF] [bit] NULL,
 CONSTRAINT [PK_BI_PARAMETERS] PRIMARY KEY NONCLUSTERED 
(
	[PARAM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
