/****** Object:  Table [dbo].[BI_PARAMETERS_LIBELLE]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[BI_PARAMETERS_LIBELLE](
	[PARAM_LIB_ID] [int] NOT NULL,
	[PARAM_LIB_LIBELLE] [nvarchar](50) NULL,
 CONSTRAINT [PK_BI_PARAMETERS_LIBELLES] PRIMARY KEY NONCLUSTERED 
(
	[PARAM_LIB_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
