/****** Object:  Table [dbo].[F020ADR]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[F020ADR](
	[F020KY] [nvarchar](20) NOT NULL,
	[F020DIRECT] [nvarchar](40) NULL,
	[F020RAISON] [nvarchar](150) NULL,
	[F020RESPON] [nvarchar](40) NULL,
	[K020T14FCT] [nvarchar](20) NULL,
	[F020ADRES1] [nvarchar](150) NULL,
	[F020ADRES2] [nvarchar](150) NULL,
	[F020VILLE] [nvarchar](150) NULL,
	[F020CP] [nvarchar](20) NULL,
	[F020SIRET] [nvarchar](20) NULL,
	[K020T53CTY] [nvarchar](20) NULL,
	[F020ANA] [nvarchar](20) NULL,
	[F020ACTIF] [char](1) NOT NULL,
	[F020ADRES3] [nvarchar](150) NULL,
	[F020ADRES4] [nvarchar](150) NULL,
	[F020DTDEB] [datetime] NULL,
	[F020DTFIN] [datetime] NULL,
	[K020001SOC] [nvarchar](20) NULL,
	[K020030AGE] [nvarchar](20) NULL,
	[K020000USR] [int] NULL,
	[F020QUAI] [char](1) NULL,
	[F020LATITUDE] [float] NULL,
	[F020LONGITUDE] [float] NULL,
	[K020TI8STA] [nvarchar](20) NULL,
	[F020ANGLEMAPS] [int] NULL,
	[F020MOISACTI] [nvarchar](12) NULL,
	[F020LATITUDE2] [decimal](23, 8) NULL,
	[F020LONGITUDE2] [decimal](23, 8) NULL,
 CONSTRAINT [PK_F020ADR] PRIMARY KEY CLUSTERED 
(
	[F020KY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [A020T53CTY_FK] ON [dbo].[F020ADR]
(
	[K020T53CTY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [FK_A020T14FCT] ON [dbo].[F020ADR]
(
	[K020T14FCT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [I_FK_A020001SOC] ON [dbo].[F020ADR]
(
	[K020001SOC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [I_K020000USR] ON [dbo].[F020ADR]
(
	[K020000USR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [I_K020030AGE] ON [dbo].[F020ADR]
(
	[K020030AGE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [I020ADR1] ON [dbo].[F020ADR]
(
	[F020VILLE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [I020ADR2] ON [dbo].[F020ADR]
(
	[F020CP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [I020ADR3] ON [dbo].[F020ADR]
(
	[F020SIRET] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
ALTER TABLE [dbo].[F020ADR] ADD  CONSTRAINT [DF_F020ADR_F020ACTIF]  DEFAULT ('1') FOR [F020ACTIF]
ALTER TABLE [dbo].[F020ADR] ADD  CONSTRAINT [DF__F020ADR__F020QUA__66BCC4C3]  DEFAULT ('2') FOR [F020QUAI]
ALTER TABLE [dbo].[F020ADR] ADD  CONSTRAINT [DF__F020ADR__F020LAT__67B0E8FC]  DEFAULT ((0)) FOR [F020LATITUDE]
ALTER TABLE [dbo].[F020ADR] ADD  CONSTRAINT [DF__F020ADR__F020LON__68A50D35]  DEFAULT ((0)) FOR [F020LONGITUDE]
ALTER TABLE [dbo].[F020ADR] ADD  DEFAULT ('222222222222') FOR [F020MOISACTI]
ALTER TABLE [dbo].[F020ADR] ADD  DEFAULT ((0)) FOR [F020LATITUDE2]
ALTER TABLE [dbo].[F020ADR] ADD  DEFAULT ((0)) FOR [F020LONGITUDE2]
ALTER TABLE [dbo].[F020ADR]  WITH CHECK ADD  CONSTRAINT [CKC_F020ACTIF_F020ADR] CHECK  (([F020ACTIF]>='1' AND [F020ACTIF]<='2'))
ALTER TABLE [dbo].[F020ADR] CHECK CONSTRAINT [CKC_F020ACTIF_F020ADR]
ALTER TABLE [dbo].[F020ADR]  WITH CHECK ADD  CONSTRAINT [CKC_F020ADR_F020QUAI] CHECK  (([F020QUAI]>='1' AND [F020QUAI]<='2'))
ALTER TABLE [dbo].[F020ADR] CHECK CONSTRAINT [CKC_F020ADR_F020QUAI]
ALTER TABLE [dbo].[F020ADR]  WITH CHECK ADD  CONSTRAINT [CV_F020ADR_F020ACTIF] CHECK  (([F020ACTIF]<>''))
ALTER TABLE [dbo].[F020ADR] CHECK CONSTRAINT [CV_F020ADR_F020ACTIF]
ALTER TABLE [dbo].[F020ADR]  WITH CHECK ADD  CONSTRAINT [CV_F020ADR_F020KY] CHECK  (([F020KY]<>''))
ALTER TABLE [dbo].[F020ADR] CHECK CONSTRAINT [CV_F020ADR_F020KY]
