/****** Object:  Table [dbo].[F03XSECT]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[F03XSECT](
	[F03XKY] [nvarchar](20) NOT NULL,
	[K03X033SECT] [nvarchar](20) NOT NULL,
	[K03X030AGE] [nvarchar](20) NULL,
	[F03XORDRE] [nvarchar](20) NULL,
	[K03X033RAT] [nvarchar](20) NULL,
	[K03XT88NAT] [nvarchar](20) NULL,
	[F03XDTDEB] [datetime] NULL,
	[F03XDTFIN] [datetime] NULL,
	[K03X001SOC] [nvarchar](20) NULL,
	[K03XT88NAT2] [nvarchar](20) NULL,
 CONSTRAINT [PK_F03XSECT] PRIMARY KEY CLUSTERED 
(
	[F03XKY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [FK_A03X030AGE] ON [dbo].[F03XSECT]
(
	[K03X030AGE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [FK_A03X033SECT] ON [dbo].[F03XSECT]
(
	[K03X033SECT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [I_K03X001SOC] ON [dbo].[F03XSECT]
(
	[K03X001SOC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [I_K03X033RAT] ON [dbo].[F03XSECT]
(
	[K03X033RAT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
ALTER TABLE [dbo].[F03XSECT]  WITH CHECK ADD  CONSTRAINT [CV_F03XSECT_F03XKY] CHECK  (([F03XKY]<>''))
ALTER TABLE [dbo].[F03XSECT] CHECK CONSTRAINT [CV_F03XSECT_F03XKY]
