/****** Object:  Table [dbo].[F051RIB]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[F051RIB](
	[F051KY] [nvarchar](20) NOT NULL,
	[K051050TIE] [nvarchar](20) NOT NULL,
	[F051BQE] [nvarchar](20) NULL,
	[F051GUI] [nvarchar](20) NULL,
	[F051CPT] [nvarchar](20) NULL,
	[F051CLE] [nvarchar](30) NULL,
	[F051DOMIC] [nvarchar](150) NULL,
	[F051ORDRE] [int] NOT NULL,
	[F051ACTIF] [char](1) NOT NULL,
	[F051IBAN] [nvarchar](34) NULL,
	[K051051NEWRIB] [nvarchar](20) NULL,
	[F051DTDEB] [datetime] NULL,
	[F051DTFIN] [datetime] NULL,
	[F051NOM] [nvarchar](80) NULL,
	[K051050TIERIB] [nvarchar](20) NULL,
	[F051BIC] [nvarchar](11) NULL,
	[F051DTMAJ] [datetime] NULL,
	[K051T05TYP] [nvarchar](20) NULL,
 CONSTRAINT [PK_F051RIB] PRIMARY KEY CLUSTERED 
(
	[F051KY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [FK_A051050TIE] ON [dbo].[F051RIB]
(
	[K051050TIE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [I_K051050TIERIB] ON [dbo].[F051RIB]
(
	[K051050TIERIB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [I_K051051NEWRIB] ON [dbo].[F051RIB]
(
	[K051051NEWRIB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
ALTER TABLE [dbo].[F051RIB] ADD  CONSTRAINT [DF_F051RIB_F051ORDRE]  DEFAULT ((1)) FOR [F051ORDRE]
ALTER TABLE [dbo].[F051RIB] ADD  CONSTRAINT [DF_F051RIB_F051ACTIF]  DEFAULT ('1') FOR [F051ACTIF]
ALTER TABLE [dbo].[F051RIB]  WITH CHECK ADD  CONSTRAINT [CKC_F051ACTIF_F051RIB] CHECK  (([F051ACTIF]>='1' AND [F051ACTIF]<='2'))
ALTER TABLE [dbo].[F051RIB] CHECK CONSTRAINT [CKC_F051ACTIF_F051RIB]
ALTER TABLE [dbo].[F051RIB]  WITH CHECK ADD  CONSTRAINT [CV_F051RIB_F051ACTIF] CHECK  (([F051ACTIF]<>''))
ALTER TABLE [dbo].[F051RIB] CHECK CONSTRAINT [CV_F051RIB_F051ACTIF]
ALTER TABLE [dbo].[F051RIB]  WITH CHECK ADD  CONSTRAINT [CV_F051RIB_F051KY] CHECK  (([F051KY]<>''))
ALTER TABLE [dbo].[F051RIB] CHECK CONSTRAINT [CV_F051RIB_F051KY]
