/****** Object:  Table [dbo].[F05WLIE]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[F05WLIE](
	[F05WKY] [nvarchar](20) NOT NULL,
	[K05WT21LIE] [nvarchar](20) NOT NULL,
	[K05W050PERE] [nvarchar](20) NOT NULL,
	[K05W050FILS] [nvarchar](20) NOT NULL,
	[F05WDTDEB] [datetime] NULL,
	[F05WDTFIN] [datetime] NULL,
	[K05W000USR] [int] NULL,
	[K05W030AGE] [nvarchar](20) NULL,
	[K05W001SOC] [nvarchar](20) NULL,
	[F05WACTIF] [char](1) NOT NULL,
	[K05WTI8POS1] [nvarchar](20) NULL,
	[K05WTI8POS2] [nvarchar](20) NULL,
	[F05WLIB] [nvarchar](250) NULL,
	[K05WT44ACT] [nvarchar](20) NULL,
	[K05W306ANA] [nvarchar](20) NULL,
	[F05WTARIFPERE] [char](1) NULL,
 CONSTRAINT [PK_F05WLIE] PRIMARY KEY CLUSTERED 
(
	[F05WKY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[F05WLIE] ADD  CONSTRAINT [DF_F05WLIE_F05WACTIF]  DEFAULT ('1') FOR [F05WACTIF]
ALTER TABLE [dbo].[F05WLIE] ADD  CONSTRAINT [DF_F05WLIE_F05WTARIFPERE]  DEFAULT ('2') FOR [F05WTARIFPERE]
ALTER TABLE [dbo].[F05WLIE]  WITH CHECK ADD  CONSTRAINT [CKC_F05WACTIF_F05WLIE] CHECK  (([F05WACTIF]>='1' AND [F05WACTIF]<='2'))
ALTER TABLE [dbo].[F05WLIE] CHECK CONSTRAINT [CKC_F05WACTIF_F05WLIE]
ALTER TABLE [dbo].[F05WLIE]  WITH CHECK ADD  CONSTRAINT [CKC_F05WTARIFPERE_F05WLIE] CHECK  (([F05WTARIFPERE]>='1' AND [F05WTARIFPERE]<='2'))
ALTER TABLE [dbo].[F05WLIE] CHECK CONSTRAINT [CKC_F05WTARIFPERE_F05WLIE]
ALTER TABLE [dbo].[F05WLIE]  WITH CHECK ADD  CONSTRAINT [CV_F05WLIE_F05WKY] CHECK  (([F05WKY]<>''))
ALTER TABLE [dbo].[F05WLIE] CHECK CONSTRAINT [CV_F05WLIE_F05WKY]
