/****** Object:  Table [dbo].[F091IMMAT]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[F091IMMAT](
	[F091KY] [nvarchar](20) NOT NULL,
	[K091090UNI] [nvarchar](20) NOT NULL,
	[F091IMMA] [nvarchar](30) NOT NULL,
	[F091IMMADT] [datetime] NOT NULL,
	[F091DEP] [nvarchar](20) NULL,
 CONSTRAINT [PK_F091IMMAT] PRIMARY KEY CLUSTERED 
(
	[F091KY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
