/****** Object:  Table [dbo].[F10VLIG]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[F10VLIG](
	[F10VKY] [nvarchar](20) NOT NULL,
	[K10V100PDT] [nvarchar](20) NOT NULL,
	[K10VT01GRP] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_F10VLIG] PRIMARY KEY CLUSTERED 
(
	[F10VKY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
