/****** Object:  Table [dbo].[F300CPTE]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[F300CPTE](
	[F300KY] [nvarchar](20) NOT NULL,
	[F300DIRECT] [nvarchar](20) NULL,
	[L300901NUM] [nvarchar](20) NOT NULL,
	[F300CENTRAL] [char](1) NOT NULL,
	[K300T39COL] [nvarchar](20) NOT NULL,
	[F300ACTIF] [char](1) NOT NULL,
	[F300RGLMANU] [char](1) NOT NULL,
	[F300POINTAGE] [char](1) NOT NULL,
	[F300LETTRAGE] [char](1) NOT NULL,
	[K300TK1TYPCPT] [nvarchar](20) NULL,
	[F300PROVISION] [char](1) NOT NULL,
	[F300LIENTVA] [char](1) NOT NULL,
	[F300CODE] [nvarchar](20) NULL,
	[K300001SOC] [nvarchar](20) NULL,
	[F300ANALYTIQUE] [char](1) NOT NULL,
 CONSTRAINT [PK_F300CPTE] PRIMARY KEY CLUSTERED 
(
	[F300KY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
