/****** Object:  Table [dbo].[F310JRX]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[F310JRX](
	[F310KY] [nvarchar](20) NOT NULL,
	[L310901NUM] [nvarchar](20) NOT NULL,
	[F310CENTRAL] [char](1) NOT NULL,
	[K310300CPT] [nvarchar](20) NULL,
	[K310T40TYP] [nvarchar](20) NOT NULL,
	[F310ACTIF] [char](1) NOT NULL,
	[F310PASAGREG] [char](1) NULL,
	[F310CODE] [nvarchar](20) NULL,
	[K310001SOC] [nvarchar](20) NULL,
	[F310ANALYTIQUE] [char](1) NOT NULL,
 CONSTRAINT [PK_F310JRX] PRIMARY KEY CLUSTERED 
(
	[F310KY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
